name: test_homepage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - name: Start Selenoid Server
      uses: Xotabu4/selenoid-github-action@v2
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Change permissions 
      run: git update-index --chmod=+x 79a2cd2e-70d5-48e7-8f1c-62aebe490ca1.sh
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: test_homepage.py
        pytest -s -v
